@IsTest
private class MetadataServiceTest {
    @IsTest
    private static void coverTest() {
        new MetadataService.RemoteSiteSetting();
        new MetadataService.CspTrustedSite();
        new MetadataService.ReadRemoteSiteSettingResult();
        new MetadataService.readRemoteSiteSettingResponse_element();
        new MetadataService.ReadCspTrustedSiteResult();
        new MetadataService.readCspTrustedSiteResponse_element();
        new MetadataService.upsertMetadataResponse_element();
        new MetadataService.upsertMetadata_element();
        new MetadataService.DebuggingHeader_element();
        new MetadataService.CallOptions_element();
        new MetadataService.DebuggingInfo_element();
        new MetadataService.AllOrNoneHeader_element();
        new MetadataService.Error();
        new MetadataService.ExtendedErrorDetails();
        new MetadataService.LogInfo();
    }
}
